// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type Resp struct {
	Code int64       `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

type ChatGptQuestionRequest struct {
	StreamId string `json:"stream_id,optional"`
	Question string `json:"question"`
}

type ChatGptQuestionResponse struct {
	Q      string `json:"q"`
	Answer string `json:"answer"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
