// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type Resp struct {
	Code int64       `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

type ChatGptQuestionRequest struct {
	StreamId string `json:"stream_id,optional"`
	Question string `json:"question"`
}

type ChatGptQuestionResponse struct {
	Q      string `json:"q"`
	Answer string `json:"answer"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type MsgOptions struct {
	ParentMessageId string `json:"parentMessageId,optional"`
}

type ChatProcessRequest struct {
	StreamId       string     `json:"stream_id,optional"`
	ConversationId string     `json:"conversation_id,optional"`
	Prompt         string     `json:"prompt"`
	Mode           string     `json:"mode,optional"`
	Options        MsgOptions `json:"options"`
	SystemMessage  string     `json:"systemMessage,optional"`
	Temperature    float32    `json:"temperature,optional"`
	TopP           float32    `json:"top_p,optional"`
}

type ChatProcessResponse struct {
	Role            string `json:"role"`
	Id              string `json:"id"`
	ParentMessageId string `json:"parentMessageId,optional"`
	Text            string `json:"text"`
	FinishReason    string `json:"finish_reason"`
	Model           string `json:"model"`
	DeltaText       string `json:"delta_text"`
}
